# Generated by Django 3.2.5 on 2021-07-22 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommercesite', '0003_rename_user_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='country',
        ),
        migrations.RemoveField(
            model_name='member',
            name='gender',
        ),
    ]
